### PR TITLE
Train Horn SFX

### PR DESCRIPTION
**Pull request by Technet9090**

### CODE REVIEW

**Comment by NazmusLabs** [comment]
What train is this?
*Edit* I have just checked the files added, and it seems as if you added horns for all three trains! Nice!

Also, do you want me to add your real name when I credit these sound files to you in their Metadata? Right now, I have only added "Technet9090" to the Metadata. Thanks!

**Comment by Technet9090** [comment]
My nickname will do the job, btw, I can add some data to the metadata myself if you'd like that!

**Comment by NazmusLabs** [comment]
Of course! But you will need to first clone this repository on your computer and change the Metadata from File Explorer. I don't think GitHub allows you to change file Metadata from the website.

**Comment by Technet9090** [comment]
What I meant, is I can do it with an app in my phone!

**Comment by NazmusLabs** [comment]
@Technet9090 oh, I see, you mean add the Metadata from the file manager in your phone. Sure, that makes sense!

**Pull request merged**
